
import React, { useState } from 'react';

interface HeroProps {
    onSearch: (query: string) => void;
}

const Hero: React.FC<HeroProps> = ({ onSearch }) => {
    const [query, setQuery] = useState('');

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        onSearch(query);
    }

    return (
        <div className="bg-gradient-to-b from-slate-900 to-slate-800 py-20 px-4 text-center">
            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-extrabold text-white tracking-tight">
                Discover Your Next Passion
            </h1>
            <p className="mt-4 max-w-2xl mx-auto text-lg text-slate-300">
                Explore thousands of courses on any topic imaginable, with content generated by the power of AI.
            </p>
            <form onSubmit={handleSubmit} className="mt-8 max-w-xl mx-auto flex">
                <input
                    type="text"
                    value={query}
                    onChange={(e) => setQuery(e.target.value)}
                    placeholder="What do you want to learn?"
                    className="w-full px-5 py-3 border border-slate-700 rounded-l-md bg-slate-800 text-white placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-indigo-500 transition-shadow"
                />
                <button type="submit" className="px-6 py-3 bg-indigo-600 text-white font-semibold rounded-r-md hover:bg-indigo-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-slate-900 focus:ring-indigo-500 transition-colors">
                    Search
                </button>
            </form>
        </div>
    );
};

export default Hero;
